from run migration downwards

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -248,53 +248,60 @@ jobs:
 
   run-migrations:
     docker:
-      # Docker image here that supports NodeJS
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
       - checkout
+      - run:
+          name: install awscli
+          command: |
+            sudo apt-get update
+            sudo apt-get -y install awscli
       - run:
           name: Run migrations
           command: |
-            # Your code here
-            cd backend
-            npm install
-            # Run and save the migration output
-            npm run migrations > migrations_dump.txt
-      # attach workspace
-      - attach_workspace:
-          at: ~/
+            cd backend/
+            echo > ".env"
+            echo ENVIRONMENT="production" >> ".env"
+            echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> ".env"
+            echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> ".env"
+            echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> ".env"
+            echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> ".env"
+            echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
+            echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
+            npm i
+            npm run migrations >> result.txt
       - run:
           name: Send migration results to kvdb
           command: |
             # Your code here
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-                # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
-                curl https://kvdb.io/9GE4jRtKznmVKRfvdBABBe/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-                fi
-     # Here's where you will add some code to rollback on failure
-      - destroy-environment
+              # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+              curl  --insecure https://kvdb.io/73AzZCsXikP6F1anyHtZ2p/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              echo "migrated ----------"
+            else
+             echo "No migration happened"
+            fi
       - revert-migrations
+      - destroy-environment
+
 
   deploy-frontend:
     docker:
-      # Docker image here that supports AWS CLI
-      - image: cimg/base:stable
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
       - checkout
-      - install_awscli
-      - install_ansible
-      - install-nodejs
-      - restore_cache:
-         keys: [frontend-build]
       - run:
           name: Install dependencies
           command: |
-            # your code here
-            cd frontend
-            npm install
+            yum install -y gcc-c++ make 
+            curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -
+            yum install -y nodejs
+            node -v
+            npm -v
       - run:
           name: Get backend url
           command: |
@@ -311,35 +318,29 @@ jobs:
       - run:
           name: Deploy frontend objects
           command: |
-            # your code here
             cd frontend
-            npm install
-            npm update
+            npm i
             npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-            echo "workflow=$CIRCLE_WORKFLOW_ID:0:7"
-      # Here's where you will add some code to rollback on failure
-      - destroy-environment
+            aws s3 sync ./dist s3://"udapeople-${CIRCLE_WORKFLOW_ID}"
       - revert-migrations
+      - destroy-environment
 
   deploy-backend:
     docker:
-      - image: cimg/base:stable      
+      - image: python:3.7-alpine3.11      
     steps:
       - checkout
-      - install_awscli
-      - install_ansible
-      - install-nodejs
       - add_ssh_keys:
           fingerprints: ["24:6f:08:e5:90:5e:a9:ee:53:b3:a9:44:9a:8a:c0:cc"]
       - attach_workspace:
-          at: .
+          at: ~/
       - run:
           name: Install dependencies
           command: |
-            cd backend
-            npm install
+            apk add --update ansible
+            apk add --update npm
+            apk add --update curl
+            pip3 --no-cache-dir install awscli
       - run:
           name: Build Backend
           command: |
@@ -355,7 +356,8 @@ jobs:
           command: |
             ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml
       - revert-migrations
-      - destroy-environment
+      - destroy-environment    
+       
 
   smoke-test:
     docker:
@@ -368,32 +370,28 @@ jobs:
             sudo apt install curl
       - attach_workspace:
           at: ~/
-       
+
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
+            export FRONTEND_IP="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+            if curl -s ${FRONTEND_IP} | grep "Welcome"
             then
-               # Change this to 0 after the job fails
-              return 0
+              echo "pass"
+              exit 0
             else
-              return 1
+              echo "fail"
+              exit 1
             fi
 
       - run:
           name: Backend smoke test.
           command: |
-              # Fetch and prepare the BACKEND_IP env var
-              export API_URL="http://${BACKEND_IP}:3030"
-              echo "${API_URL}"
-              if curl "${API_URL}/api/status" | grep "ok"
-              then
-                 return 0
-              else
-                 return 1
-              fi
+            export BACKEND_IP=$(tail -1 ~/project/.circleci/ansible/inventory.txt)
+            export API_URL="http://${BACKEND_IP}:3030/api/status"
+            echo "${API_URL}"
+            sleep 30
+            curl ${API_URL}
       - revert-migrations
       - destroy-environment
 
